### PR TITLE
Updates to FSLTL Injector content

### PR DESCRIPTION
**Pull request by whakamolenz**
Add FSLTL SU12 beta release as experimental download
Move FSLTL Injector to github endpoints

### CODE REVIEW

**Comment by whakamolenz** [comment]
Hi team - this is an update we need to make for the installer content for the injector for FSLTL. Mainly we need to move our end point for it from our web host to github due to bandwidth issues. But additionally we want to add an experimental build for SU12. Can we get this added to staging so i can get our testers to check from the cdn copy of the file.

**Comment by frankkopp** [comment]
Will look at it ...

**Comment by frankkopp** [comment]
Merged to Staging - please test and report back if ok

**Comment by whakamolenz** [comment]
> Merged to Staging - please test and report back if ok

Initial tests look good - our broader test team are just finishing up their trials over the next day or so. Then can confirm good for release.

**Comment by whakamolenz** [comment]
> Merged to Staging - please test and report back if ok

We have fully tested and are happy for this to go to production when possible. Thank you!

**Comment by frankkopp** [comment]
I'll put it on production then :)

**Pull request merged**
